---
#Название PB
- name: Проверка активности камер
#На какие hosts будем его применять  
  hosts: all
  gather_facts: no
  tasks:
  - name: Выполнение команды Camera
    raw: |
            hostname -I
            curl -s http://agent:DK98utVP@localhost:8080/channel/videoParameters | jq .[].id | wc -l
            curl -s http://agent:DK98utVP@localhost:8080/channel/videoParameters | jq . | grep -ce '"status": 0'
            curl -s http://agent:DK98utVP@localhost:8080/channel/videoParameters | jq . | grep -ce '"status": 1'
    register: camera_status
    ignore_errors: true
    check_mode: no
  - name: Выводим состояние по Camera в файл
    lineinfile:
      dest: "/root/Documents/camera_status/camera_status.csv"
      line: "{{ camera_status }}"
      insertafter: EOF
